### ISSUE TITLE
Licensing the repo

### ISSUE THREAD

**Issue by bebosudo** [ypsman/ansible-ipv6-disable#5]
Hi, it would be an interesting and useful repo but it doesn't have a license.
Could you please provide one? I usually go with MIT for personal projects.
https://help.github.com/en/github/creating-cloning-and-archiving-repositories/licensing-a-repository

If you want I can provide you with a Pull Request with the license of your choice.

**Comment by ypsman** [comment]
Sorry for my late Comment, You can make a PR with the License if you want.

**Comment by bebosudo** [comment]
I moved to another job, so it doesn't matter to me anymore, but you can add a new license with a couple of clicks from the github web interface:
https://docs.github.com/en/free-pro-team@latest/github/building-a-strong-community/adding-a-license-to-a-repository

**Comment by ypsman** [comment]
Ty for the Tip with the Web Interface.
